import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Outfit } from 'next/font/google'
import AdContainer from "./_compoents/AdContainer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ["latin"], display: "swap" });


export default function RootLayout({ children }) {
  return (
    <ClerkProvider isomorphic>
      <html lang="en" key="html-root">
        <body suppressHydrationWarning={true} className={outfit.className} key="body-root">

          {children}
          {/* <AdContainer /> */}
        </body>
      </html>
    </ClerkProvider>

  );
}
